// Mock data for development without database
import type { Product, Commodity, Partner } from "./types"

export const mockCommodities: Commodity[] = [
  {
    id: "1",
    name: "Digital Services",
    code: "DS001",
    description: "Digital service offerings",
    category: "Technology",
    status: "active",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    name: "Financial Products",
    code: "FP001",
    description: "Financial service products",
    category: "Finance",
    status: "active",
    created_at: "2024-01-16T10:00:00Z",
    updated_at: "2024-01-16T10:00:00Z",
  },
  {
    id: "3",
    name: "Real Estate",
    code: "RE001",
    description: "Real estate financing products",
    category: "Property",
    status: "active",
    created_at: "2024-01-17T10:00:00Z",
    updated_at: "2024-01-17T10:00:00Z",
  },
]

export const mockPartners: Partner[] = [
  {
    id: "1",
    name: "TechCorp Solutions",
    email: "contact@techcorp.com",
    phone: "+1-555-0123",
    company: "TechCorp Inc.",
    status: "active",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-10T10:00:00Z",
  },
  {
    id: "2",
    name: "Global Finance Ltd",
    email: "info@globalfinance.com",
    phone: "+1-555-0456",
    company: "Global Finance Limited",
    status: "active",
    created_at: "2024-01-12T10:00:00Z",
    updated_at: "2024-01-12T10:00:00Z",
  },
  {
    id: "3",
    name: "Saudi Investment Bank",
    email: "products@sib.com.sa",
    phone: "+966-11-123-4567",
    company: "Saudi Investment Bank",
    status: "active",
    created_at: "2024-01-14T10:00:00Z",
    updated_at: "2024-01-14T10:00:00Z",
  },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Home Financing Plus",
    name_ar: "التمويل العقاري بلس",
    description: "Comprehensive home financing solution with competitive rates and flexible terms",
    description_ar: "حل تمويل عقاري شامل بأسعار تنافسية وشروط مرنة",
    logo_url: "/abstract-bank-logo.png",
    notification_email: "home-financing@bank.com",
    country: "SA",
    master_category: "Murabaha",
    sub_categories: ["Home Purchase", "Construction"],
    customer_types: ["Individual", "SME"],
    commodity_id: "3",
    commodity: mockCommodities[2],
    status: "active",
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-01-20T10:00:00Z",
    created_by: "admin@bank.com",
    partner_id: "3",
    partner: mockPartners[2],
  },
  {
    id: "2",
    name: "Business Growth Financing",
    name_ar: "تمويل نمو الأعمال",
    description: "Flexible business financing for growth and expansion with Sharia-compliant terms",
    description_ar: "تمويل أعمال مرن للنمو والتوسع بشروط متوافقة مع الشريعة",
    logo_url: "/business-growth-path.png",
    notification_email: "business-finance@bank.com",
    country: "SA",
    master_category: "Ijarah",
    sub_categories: ["Equipment Financing", "Working Capital"],
    customer_types: ["Business", "SME", "Corporate"],
    commodity_id: "2",
    commodity: mockCommodities[1],
    status: "active",
    created_at: "2024-01-22T10:00:00Z",
    updated_at: "2024-01-22T10:00:00Z",
    created_by: "admin@bank.com",
    partner_id: "2",
    partner: mockPartners[1],
  },
  {
    id: "3",
    name: "Digital Payment Solutions",
    name_ar: "حلول الدفع الرقمي",
    description: "Modern BNPL solution for e-commerce and retail with instant approval",
    description_ar: "حل حديث للشراء الآن والدفع لاحقاً للتجارة الإلكترونية والتجزئة مع الموافقة الفورية",
    logo_url: "/digital-payment.png",
    notification_email: "digital-payments@bank.com",
    country: "AE",
    master_category: "BNPL",
    sub_categories: ["E-commerce", "Retail"],
    customer_types: ["Individual", "Business"],
    commodity_id: "1",
    commodity: mockCommodities[0],
    status: "draft",
    created_at: "2024-01-25T10:00:00Z",
    updated_at: "2024-01-25T10:00:00Z",
    created_by: "admin@bank.com",
    partner_id: "1",
    partner: mockPartners[0],
  },
  {
    id: "4",
    name: "Investment Crowdfunding",
    name_ar: "التمويل الجماعي للاستثمار",
    description: "Sharia-compliant crowdfunding platform for real estate and business investments",
    description_ar: "منصة تمويل جماعي متوافقة مع الشريعة للاستثمارات العقارية والتجارية",
    logo_url: "/crowdfunding-investment.png",
    notification_email: "crowdfunding@bank.com",
    country: "SA",
    master_category: "Crowd-Funding",
    sub_categories: ["Real Estate", "Business Ventures"],
    customer_types: ["Individual", "Business", "Corporate"],
    commodity_id: "3",
    commodity: mockCommodities[2],
    status: "active",
    created_at: "2024-01-28T10:00:00Z",
    updated_at: "2024-01-28T10:00:00Z",
    created_by: "admin@bank.com",
  },
  {
    id: "5",
    name: "Auto Financing Express",
    name_ar: "التمويل السريع للسيارات",
    description: "Quick auto financing with competitive rates and minimal documentation",
    description_ar: "تمويل سريع للسيارات بأسعار تنافسية ووثائق أقل",
    logo_url: "/auto-financing.png",
    notification_email: "auto-finance@bank.com",
    country: "AE",
    master_category: "Tawarruq",
    sub_categories: ["New Cars", "Used Cars"],
    customer_types: ["Individual"],
    commodity_id: "1",
    commodity: mockCommodities[0],
    status: "inactive",
    created_at: "2024-02-01T10:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
    created_by: "admin@bank.com",
    partner_id: "1",
    partner: mockPartners[0],
  },
]

export const mockCountries = [
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼" },
  { code: "QA", name: "Qatar", flag: "🇶🇦" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭" },
]

export const productCategories = ["Murabaha", "Ijarah", "BNPL", "Crowd-Funding", "Tawarruq"]

export const customerTypes = ["Individual", "SME", "Corporate"]
