stages:
  - clone

# -----------------------------
# DEV PIPELINE
# -----------------------------
clone-dev:
  stage: clone
  tags:
    - sullis-digital
  variables:
    GIT_STRATEGY: none
  script:
    - cd /opt/react-dashboard
    - git pull origin sullis-digital
    - ./deploy.sh
    - echo "Code updated successfully"

  only:
    - sullis-digital
