stages:
  - clone

# -----------------------------
# DEV PIPELINE
# -----------------------------
clone-sullis:
  stage: clone
  tags:
    - new_mytm_dev
  variables:
    GIT_STRATEGY: none
  script:
    - cd /www/wwwroot/react-projects/financing-dashboard.xintdev.com
    - git pull origin sullis-digital
    - ./deploy.sh
    - echo "Code updated successfully"

  only:
    - sullis-digital
