import { useState, useEffect } from "react";
import { Input, Select, Switch, DatePicker } from "antd";
import toast from "react-hot-toast";
import { useTranslation } from "react-i18next";
import { useNavigate, useSearchParams } from "react-router-dom";
import { addPartnerAdmin } from "../../redux/apis/apisCrud";
import moment from "moment";

const { Option } = Select;

// Function to generate random password (max 8 characters)
const generatePassword = () => {
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let password = '';
  for (let i = 0; i < 8; i++) {
    password += characters.charAt(Math.floor(Math.random() * characters.length));
  }
  return password;
};

const AddPartnerAdmin = () => {
  const { t } = useTranslation("partner");
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const partnerId = searchParams.get("id");
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    password: "",
    phone: "",
    address: "",
    dob: "",
    country_id: "1",
    status: false,
    send_details_via_mail: false,
  });

  // Auto-generate password on component mount
  useEffect(() => {
    setFormData(prev => ({ ...prev, password: generatePassword() }));
  }, []);

  useEffect(() => {
    if (!partnerId) {
      toast.error(t("toast.partnerIdMissing"));
      navigate("/PartnerManagement/PartnersList");
    }
  }, [partnerId, navigate]);

  const handleInputChange = (field: string, value: any) => {
    setFormData({ ...formData, [field]: value });
  };

  const handleSubmit = async () => {
    try {
      // Validation
      if (!formData.name || !formData.email || !formData.phone) {
        toast.error(t("toast.fillRequired"));
        return;
      }

      if (!partnerId) {
        toast.error(t("toast.partnerIdMissing"));
        return;
      }

      setLoading(true);

      const submitData = {
        name: formData.name,
        email: formData.email,
        password: formData.password,
        phone: formData.phone,
        address: formData.address,
        dob: formData.dob,
        country_id: formData.country_id,
        status: formData.status ? "1" : "0",
        send_details_via_mail: formData.send_details_via_mail,
      };

      const response = await addPartnerAdmin(partnerId, submitData);

      if (response?.data?.success) {
        toast.success(response?.data?.message || t("toast.adminAdded"));
        navigate(`/PartnerManagement/PartnerAdminList?id=${partnerId}`);
      } else {
        toast.error(response?.data?.message || t("toast.adminAddFailed"));
      }
    } catch (error: any) {
      console.error("Error adding partner admin:", error);
      toast.error(error?.response?.data?.message || t("toast.adminAddFailed"));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="service" style={{ background: "white", padding: "2rem", borderRadius: "2px" }}>
      {/* <h4 style={{ marginBottom: "2rem" }}>Add Partner Admin</h4> */}

      <div className="row">
        {/* Name */}
        <div className="col-md-6 mb-3">
          <label className="form-label">{t("common:name")}</label>
          <Input
            placeholder={t("form.namePlaceholder")}
            value={formData.name}
            onChange={(e) => handleInputChange("name", e.target.value)}
            style={{ height: "40px" }}
          />
        </div>

        {/* Email */}
        <div className="col-md-6 mb-3">
          <label className="form-label">{t("common:email")}</label>
          <Input
            type="email"
            placeholder={t("common:email")}
            value={formData.email}
            onChange={(e) => handleInputChange("email", e.target.value)}
            style={{ height: "40px" }}
          />
        </div>

        {/* Password */}
        <div className="col-md-6 mb-3">
          <label className="form-label">{t("form.password")}</label>
          <Input
            placeholder={t("form.autoGeneratedPassword")}
            value={formData.password}
            style={{ height: "40px", backgroundColor: "var(--color-surface-muted)" }}
            readOnly
          />
        </div>

        {/* Phone */}
        <div className="col-md-6 mb-3">
          <label className="form-label">{t("common:phone")}</label>
          <Input
            addonBefore="+966"
            placeholder={t("common:phone")}
            value={formData.phone}
            onChange={(e) => handleInputChange("phone", e.target.value)}
            style={{ height: "40px" }}
          />
        </div>

        {/* Address */}
        <div className="col-md-6 mb-3">
          <label className="form-label">{t("form.address")}</label>
          <Input
            placeholder={t("form.address")}
            value={formData.address}
            onChange={(e) => handleInputChange("address", e.target.value)}
            style={{ height: "40px" }}
          />
        </div>

        {/* DOB */}
        <div className="col-md-6 mb-3">
          <label className="form-label">{t("form.dob")}</label>
          <DatePicker
            placeholder={t("form.dobPlaceholder")}
            value={formData.dob ? moment(formData.dob) : null}
            onChange={(date) => handleInputChange("dob", date ? date.format("YYYY-MM-DD") : "")}
            style={{ width: "100%", height: "40px" }}
            format="YYYY-MM-DD"
          />
        </div>

        {/* Country */}
        <div className="col-md-6 mb-3">
          <label className="form-label">{t("form.country")}</label>
          <Select
            value={formData.country_id}
            onChange={(value) => handleInputChange("country_id", value)}
            style={{ width: "100%" }}
          >
            <Option value="1">{t("form.saudiArabia")}</Option>
            {/* <Option value="2">UAE</Option>
            <Option value="3">Kuwait</Option> */}
          </Select>
        </div>

        {/* Status */}
        <div className="col-md-6 mb-3">
          <div className="d-flex align-items-center gap-2" style={{ marginTop: "28px" }}>
            <Switch
              className="red-switch"
              checked={formData.status}
              onChange={(checked) => handleInputChange("status", checked)}
            />
            <label className="form-label mb-0">{t("common:status")}</label>
          </div>
        </div>

        {/* Send Details Via Mail */}
        <div className="col-md-6 mb-3">
          <div className="d-flex align-items-center gap-2">
            <Switch
              className="red-switch"
              checked={formData.send_details_via_mail}
              onChange={(checked) => handleInputChange("send_details_via_mail", checked)}
            />
            <label className="form-label mb-0">{t("form.sendDetailsViaMail")}</label>
          </div>
        </div>
      </div>

      {/* Save Button */}
      <div className="d-flex justify-content-end mt-4">
        <button
          className="theme-btn-next"
          onClick={handleSubmit}
          disabled={loading}
        >
          {loading ? t("form.saving") : t("common:save")}
        </button>
      </div>
    </div>
  );
};

export default AddPartnerAdmin;

